apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-blueprint
  namespace: demo
  annotations:
    ktpl.io/local: "true"
spec:
  template:
    spec:
      containers:
        - name: telemetry
          image: otel/opentelemetry-collector:0.90.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  template:
    spec:
      containers:
        - name: app
          image: myorg/app:v1.0.0
          env:
            - name: PORT
              value: "8080"
        - <<: '{{ ref "demo/deployment/base-blueprint" "spec.template.spec.containers" }}'
        - name: logger
          image: fluent/fluent-bit:2.2.0
