apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
  namespace: demo
data:
  env: prod
  region: eu-west-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: demo
  labels:
    settings: '{{ ref "demo/configmap/settings" "data" }}'
