apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: shop
spec:
  replicas: '{{ ref "shop/configmap/settings" "data.replicas" | int }}'
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: '{{ ref "shop/configmap/settings" "data.image" }}'
