# New object, only present in prod.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: shop
spec:
  minAvailable: 2
  selector:
    matchLabels: '{{ ref "shop/deployment/api" "spec.selector.matchLabels" }}'
