apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: default
  labels:
    app.kubernetes.io/name: api
data:
  env: production
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  selector:
    app: '{{ ref "default/configmap/api" "metadata.labels[''app.kubernetes.io/name'']" }}'
