apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    <<: '{{ ref "argocd/configmap/ktpl-parameter" "metadata.labels" }}'
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/component: server
data:
  policy.csv: ""
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
